// Esmaül Hüsna (99 isim).
// Arapça adlar ve sıra: AlAdhan API (api.aladhan.com/v1/asmaAlHusna).
// Türkçe adlar ve anlamlar: suresioku.com "Allah'ın 99 İsmi ve Anlamları"
// sayfasından otomatik çıkarıldı (çekim: 4 Temmuz 2026), Arapça anahtarla
// eşleştirildi; elle yazılmadı, imla düzeltmesi yapılmadı.
// NOT: Kaynak listede el-Ehad (67) bulunmuyor (98 isim); harmanlama yasağı
// gereği bu girdinin latin adı AlAdhan'dan kaldı, anlamı null bırakıldı.
export const ESMA_DATA = [
  { no: 1, arapca: "الرَّحْمَنُ", latin: "er-Rahmân", anlam: "Sonsuz merhametiyle lütuf ve ihsanda bulunan." },
  { no: 2, arapca: "الرَّحِيمُ", latin: "er-Rahîm", anlam: "Rahmetiyle hey şeyi kuşatan." },
  { no: 3, arapca: "الْمَلِكُ", latin: "el-Melik", anlam: "Bütün varlıkların sahibi/hükümdârı." },
  { no: 4, arapca: "الْقُدُّوسُ", latin: "el-Kuddûs", anlam: "Eksiklik ve kusurlardan münezzeh/uzak olan, bütün kemâl sıfatları kendisinde toplayan." },
  { no: 5, arapca: "السَّلاَمُ", latin: "es-Selâm", anlam: "Esenlik ve selamet veren, yaratılmışlara özgü değişikliklerden ve yok oluştan münezzeh olan." },
  { no: 6, arapca: "الْمُؤْمِنُ", latin: "el-Mü’min", anlam: "Bütün mahlûkâta emniyet/güven veren ve kendisine güvenilen." },
  { no: 7, arapca: "الْمُهَيْمِنُ", latin: "el-Müheymin", anlam: "Kâinatın bütün işlerini gözetip yöneten, her şeyi hükmü altına alan." },
  { no: 8, arapca: "الْعَزِيزُ", latin: "el-Azîz", anlam: "Ulu, galip, her şeye üstün gelen izzet sahibi." },
  { no: 9, arapca: "الْجَبَّارُ", latin: "el-Cebbâr", anlam: "Dilediğini yaptırma gücüne sahip olan, her şeyi tasarrufu altına alan ve iradesini her durumda yürüten." },
  { no: 10, arapca: "الْمُتَكَبِّرُ", latin: "el-Mütekebbir", anlam: "Büyüklüğünü izhar eden, son derece ulu, yüce." },
  { no: 11, arapca: "الْخَالِقُ", latin: "el-Hâlik", anlam: "Her şeyin yaratıcısı, hikmeti gereği her şeyi ölçülü yaratan." },
  { no: 12, arapca: "الْبَارِئُ", latin: "el-Bâri’", anlam: "Yoktan yaratan, maddesi ve örneği olmadan îcat eden." },
  { no: 13, arapca: "الْمُصَوِّرُ", latin: "el-Musavvir", anlam: "Varlığa şekil ve sûret veren." },
  { no: 14, arapca: "الْغَفَّارُ", latin: "el-Gaffâr", anlam: "Kusur ve günahları örten, çokça bağışlayan." },
  { no: 15, arapca: "الْقَهَّارُ", latin: "el-Kahhâr", anlam: "Yenilmeyen, dilediğini yerine getiren, kendisine her şeyin boyun eğdiği yegâne kudret ve tasarruf sahibi." },
  { no: 16, arapca: "الْوَهَّابُ", latin: "el-Vehhâb", anlam: "Karşılıksız olarak çokça nimet veren ve ihsanda bulunan." },
  { no: 17, arapca: "الرَّزَّاقُ", latin: "er-Rezzâk", anlam: "Maddî ve manevî bol rızık veren, her türlü rızık imkânlarını yaratan." },
  { no: 18, arapca: "الْفَتَّاحُ", latin: "el-Fettâh", anlam: "Hayır kapılarını açan, hükmüyle adaleti sağlayan." },
  { no: 19, arapca: "اَلْعَلِيْمُ", latin: "el-Alîm", anlam: "İlmi her şeyi kuşatan." },
  { no: 20, arapca: "الْقَابِضُ", latin: "el-Kâbız", anlam: "Her şeyi teslim alan, hikmeti gereği rızkı ve her türlü nimeti ölçülü veren, eceli gelenlerin ruhlarını teslim alan." },
  { no: 21, arapca: "الْبَاسِطُ", latin: "el-Bâsıt", anlam: "Rızkı ve her türlü rızık imkânını genişleten, ömürleri uzatan." },
  { no: 22, arapca: "الْخَافِضُ", latin: "el-Hâfıd", anlam: "Kâfirleri ve zalimleri alçaltan." },
  { no: 23, arapca: "الرَّافِعُ", latin: "er-Râfi`", anlam: "Müminleri yükselten, izzetli ve şerefli kılan." },
  { no: 24, arapca: "الْمُعِزُّ", latin: "el-Muizz", anlam: "Yücelten, güçlü ve aziz kılan." },
  { no: 25, arapca: "المُذِلُّ", latin: "el-Müzill", anlam: "Boyun eğdiren, değersiz kılan." },
  { no: 26, arapca: "السَّمِيعُ", latin: "es-Semî`", anlam: "Her şeyi işiten." },
  { no: 27, arapca: "الْبَصِيرُ", latin: "el-Basîr", anlam: "Her şeyi gören." },
  { no: 28, arapca: "الْحَكَمُ", latin: "el-Hakem", anlam: "Nihâî hükmü veren." },
  { no: 29, arapca: "الْعَدْلُ", latin: "el-Adl", anlam: "Adaletli, her şeyi yerli yerinde yapan." },
  { no: 30, arapca: "اللَّطِيفُ", latin: "el-Latîf", anlam: "En gizli ve ince hususları dahi bilen, lütufta bulunan, zâtı duyularla algılanamayan, fiillerini rıfk ile gerçekleştiren." },
  { no: 31, arapca: "الْخَبِيرُ", latin: "el-Habîr", anlam: "Gizli ve açık her şeyden haberdar olan, dilediğini haber veren." },
  { no: 32, arapca: "الْحَلِيمُ", latin: "el-Halîm", anlam: "Sabırlı, acele ve kızgınlıkla muamele etmeyen, kudreti olduğu hâlde hemen cezalandırmayan." },
  { no: 33, arapca: "الْعَظِيمُ", latin: "el-Azîm", anlam: "Zat ve sıfatları bakımından pek yüce olan, azametli olan." },
  { no: 34, arapca: "الْغَفُورُ", latin: "el-Gafûr", anlam: "Çok affedici ve bağışlayıcı olan." },
  { no: 35, arapca: "الشَّكُورُ", latin: "eş-Şekûr", anlam: "Yapılan iyi amellerin karşılığını bolca veren." },
  { no: 36, arapca: "الْعَلِيُّ", latin: "el-Aliyy", anlam: "Yücelik ve hükümranlıkta kendisine eşit veya kendisinden daha üstün bir varlık bulunmayan." },
  { no: 37, arapca: "الْكَبِيرُ", latin: "el-Kebîr", anlam: "Zâtının ve sıfatlarının mahiyeti bilinemeyecek kadar büyük ve ulu olan." },
  { no: 38, arapca: "الْحَفِيظُ", latin: "el-Hafîz", anlam: "Her şey gözetiminde olan, koruyan ve kainatı dengede tutan." },
  { no: 39, arapca: "المُقيِت", latin: "el-Mukît", anlam: "Mahlukatın gıdasını yaratıp veren, güç yetiren ve koruyup gözeten." },
  { no: 40, arapca: "الْحسِيبُ", latin: "el-Hasîb", anlam: "Hesaba çeken, her şeyin neticesini bilen." },
  { no: 41, arapca: "الْجَلِيلُ", latin: "el-Celîl", anlam: "Hiçbir kayıt ve kıyas kabul etmeksizin azamet sahibi, kıymeti ve mertebesi en yüce olan." },
  { no: 42, arapca: "الْكَرِيمُ", latin: "el-Kerîm", anlam: "Çok cömert, nimet ve ihsanı bol olan." },
  { no: 43, arapca: "الرَّقِيبُ", latin: "er-Rakîb", anlam: "Gözeten, koruyan ve bütün işler murakabesi/kontrolü altında olan." },
  { no: 44, arapca: "الْمُجِيبُ", latin: "el-Mücîb", anlam: "Dua ve dilekleri kabul eden." },
  { no: 45, arapca: "الْوَاسِعُ", latin: "el-Vâsi`", anlam: "İlmi, rahmeti ve kudreti her şeyi kuşatan." },
  { no: 46, arapca: "الْحَكِيمُ", latin: "el-Hakîm", anlam: "Her işi, emri ve yasağı yerli yerinde olan." },
  { no: 47, arapca: "الْوَدُودُ", latin: "el-Vedûd", anlam: "Müminleri seven ve onlar tarafından da sevilen." },
  { no: 48, arapca: "الْمَجِيدُ", latin: "el-Mecîd", anlam: "Her türlü eksiklikten münezzeh, lütuf ve ikramı bol olan." },
  { no: 49, arapca: "الْبَاعِثُ", latin: "el-Bâis", anlam: "Ölüleri dirilten, peygamberler gönderen." },
  { no: 50, arapca: "الشَّهِيدُ", latin: "eş-Şehîd", anlam: "Her şeye muttali olan, kendisine hiçbir şey gizli kalmayan." },
  { no: 51, arapca: "الْحَقُّ", latin: "el-Hakk", anlam: "Bizzat ve sürekli olarak var olan, varlığı kendinden olan, ulûhiyet ve rubûbiyeti gerçek olan." },
  { no: 52, arapca: "الْوَكِيلُ", latin: "el-Vekîl", anlam: "Bütün yaratıkların işlerinin görülmesinde güvenilip dayanılan, bu konuda tam yeterli olan." },
  { no: 53, arapca: "الْقَوِيُّ", latin: "el-Kavî", anlam: "Gücü ve kuvveti her şeye yeten." },
  { no: 54, arapca: "الْمَتِينُ", latin: "el-Metîn", anlam: "Acizliği, zafiyeti ve güçsüzlüğü olmayan, güçlü olan." },
  { no: 55, arapca: "الْوَلِيُّ", latin: "el-Velî", anlam: "Müminlere dost ve yardımcı olan." },
  { no: 56, arapca: "الْحَمِيدُ", latin: "el-Hamîd", anlam: "Çok övülen, bütün övgülere ve övgülerin en yücesine layık olan." },
  { no: 57, arapca: "الْمُحْصِي", latin: "el-Muhsî", anlam: "Gizli ve âşikâr her şeyin ölçü ve sayısını bütün ayrıntılarıyla bilen." },
  { no: 58, arapca: "الْمُبْدِئُ", latin: "el-Mübdi’", anlam: "Her şeyi yoktan var eden." },
  { no: 59, arapca: "الْمُعِيدُ", latin: "el-Muîd", anlam: "Varlıkları ölümlerinden sonra tekrar yaratan." },
  { no: 60, arapca: "الْمُحْيِي", latin: "el-Muhyî", anlam: "Hayat veren, yaşatan ve dirilten." },
  { no: 61, arapca: "اَلْمُمِيتُ", latin: "el-Mümît", anlam: "Öldüren, canları kabzeden." },
  { no: 62, arapca: "الْحَيُّ", latin: "el-Hayy", anlam: "Ezelî ve ebedî olarak diri ve ölümsüz olan." },
  { no: 63, arapca: "الْقَيُّومُ", latin: "el-Kayyûm", anlam: "Varlığı kendinden olan, her şeyin varlığı kendisine bağlı olan, kâinatı idare eden." },
  { no: 64, arapca: "الْوَاجِدُ", latin: "el-Vâcid", anlam: "Her şeyi bilen, hiçbir şeye muhtaç olmayan, emrini ve isteğini daima gerçekleştiren." },
  { no: 65, arapca: "الْمَاجِدُ", latin: "el-Mâcid", anlam: "Şânı yüce ve sonsuz kerem sahibi olan." },
  { no: 66, arapca: "الْواحِدُ", latin: "el-Vâhid", anlam: "Bir, tek, yegâne varlık; zâtında, ilah ve rab oluşunda ortağı olmayan." },
  { no: 67, arapca: "اَلاَحَدُ", latin: "Al Ahad", anlam: null },
  { no: 68, arapca: "الصَّمَدُ", latin: "es-Samed", anlam: "Herkesin kendisine muhtaç olduğu, kendisi ise kimseye muhtaç olmayan, ezelî ve ebedî olan." },
  { no: 69, arapca: "الْقَادِرُ", latin: "el-Kâdir", anlam: "Her şeye gücü yeten." },
  { no: 70, arapca: "الْمُقْتَدِرُ", latin: "el-Muktedir", anlam: "Güç ve kuvvetinde hiçbir sınır olmayan." },
  { no: 71, arapca: "الْمُقَدِّمُ", latin: "el-Mukaddim", anlam: "Hikmeti gereği istediğini öne alan, ileri geçiren." },
  { no: 72, arapca: "الْمُؤَخِّرُ", latin: "el-Muahhir", anlam: "Hikmeti gereği dilediğini geriye bırakan." },
  { no: 73, arapca: "الأوَّلُ", latin: "el-Evvel", anlam: "Varlığının başlangıcı olmayan, ezelî olan." },
  { no: 74, arapca: "الآخِرُ", latin: "el-Âhir", anlam: "Varlığının sonu olmayan, ebedî olan." },
  { no: 75, arapca: "الظَّاهِرُ", latin: "ez-Zâhir", anlam: "Varlığını ve birliğini belgeleyen birçok delilin bulunması açısından varlığı açık olan." },
  { no: 76, arapca: "الْبَاطِنُ", latin: "el-Bâtın", anlam: "Zâtı itibarıyla gizli olan, bütün gizlilikleri bilen." },
  { no: 77, arapca: "الْوَالِي", latin: "el-Vâlî", anlam: "Kainatı yöneten, onlar için gerekli olan her şeyi üstlenen." },
  { no: 78, arapca: "الْمُتَعَالِي", latin: "el-Müteâlî", anlam: "Noksanlıklardan berî, aşkın ve yüce olan." },
  { no: 79, arapca: "الْبَرُّ", latin: "el-Berr", anlam: "Çokça iyilik eden." },
  { no: 80, arapca: "التَّوَابُ", latin: "et-Tevvâb", anlam: "Kullarını tövbelerini kabul eden." },
  { no: 81, arapca: "الْمُنْتَقِمُ", latin: "el-Müntakım", anlam: "Suçluları yaptıklarına karşılık cezalandıran." },
  { no: 82, arapca: "العَفُوُّ", latin: "el-Afüvv", anlam: "Çokça affeden." },
  { no: 83, arapca: "الرَّؤُوفُ", latin: "er-Raûf", anlam: "Merhameti ve şefkati çok olan." },
  { no: 84, arapca: "مَالِكُ الْمُلْكِ", latin: "Mâlikü’l-mülk", anlam: "Mülkün gerçek sahibi, tüm mevcûdâtı idare eden." },
  { no: 85, arapca: "ذُوالْجَلاَلِ وَالإكْرَامِ", latin: "Zü’l-celâli ve’l-ikrâm", anlam: "Sonsuz yücelik ve ikram sahibi olan." },
  { no: 86, arapca: "الْمُقْسِطُ", latin: "el-Muksit", anlam: "Adaleti gerçekleştiren, hakkaniyetle hükmeden." },
  { no: 87, arapca: "الْجَامِعُ", latin: "el-Câmi‘", anlam: "Dünya ve ahirette bütün mahlûkâtı bir araya getirme kudretine sahip olan." },
  { no: 88, arapca: "الْغَنِيُّ", latin: "el-Ganî", anlam: "Hiçbir şeye ihtiyacı olmayan." },
  { no: 89, arapca: "الْمُغْنِي", latin: "el-Muğnî", anlam: "İhtiyaçtan kurtaran zengin kılan." },
  { no: 90, arapca: "اَلْمَانِعُ", latin: "el-Mâni`", anlam: "Hikmeti gereği engel koyan, mani olan." },
  { no: 91, arapca: "الضَّارَّ", latin: "ed-Dârr", anlam: "Hikmeti gereği elem ve zarar verici şeyleri yaratan." },
  { no: 92, arapca: "النَّافِعُ", latin: "en-Nâfi`", anlam: "hayrı ve faydayı yaratan ve veren." },
  { no: 93, arapca: "النُّورُ", latin: "en-Nûr", anlam: "Nurlandıran, her şeyi aydınlatan, kalplere nur ve iman veren." },
  { no: 94, arapca: "الْهَادِي", latin: "el-Hâdî", anlam: "Doğru yolu gösteren, hidâyete erdiren." },
  { no: 95, arapca: "الْبَدِيعُ", latin: "el-Bedî`", anlam: "Örneksiz ve benzersiz olarak yoktan yaratan." },
  { no: 96, arapca: "اَلْبَاقِي", latin: "el-Bâkî", anlam: "Varlığı sürekli olan, ebedî, sonsuz olan." },
  { no: 97, arapca: "الْوَارِثُ", latin: "el-Vâris", anlam: "Varlığının sonunun bulunmaması vasfıyla kâinatın gerçek sahibi." },
  { no: 98, arapca: "الرَّشِيدُ", latin: "er-Reşîd", anlam: "Yol gösteren, her işi isabetli olan." },
  { no: 99, arapca: "الصَّبُورُ", latin: "es-Sabûr", anlam: "Günahkârları hemen cezalandırmayıp onlara mühlet tanıyan." },
]
